INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\main\views.py", line 29, in search_page
    logging.INFO("Выполняю поиск")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:12:29] "[35m[1mGET /search?s=кот HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\main\views.py", line 29, in search_page
    logging.INFO("Выполняю поиск")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:12] "[35m[1mGET /search?s=кот HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:15] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:15] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:19] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:19] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:19] "GET /uploads/images/689269129.jpeg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:20] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\main\views.py", line 29, in search_page
    logging.INFO("Выполняю поиск")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:13:22] "[35m[1mGET /search?s= HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:14:53] "GET /search?s= HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:14:55] "GET /search?s=кот HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:14:55] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:15:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:15:51] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\main\views.py", line 29, in search_page
    logging.INFO("Выполняю поиск")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:15:53] "[35m[1mGET /search?s=кот HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Выполняю поиск
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:18:59] "GET /search?s=кот HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:18:59] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:19:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:19:01] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:23:18] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:23:18] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:23:22] "[31m[1mPOST /post HTTP/1.1[0m" 413 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:23:31] "POST /post HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:26:57] "GET /post HTTP/1.1" 200 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\loader\views.py", line 25, in add_post_page
    logging.info("Ошибка расширения файла")
AttributeError: module 'flask.logging' has no attribute 'info'
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:26:58] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:30:58] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:30:58] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:31:00] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:31:00] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rin89_000\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\rin89_000\YandexDisk\!Python\devs\hw_12\loader\views.py", line 25, in add_post_page
    logging.error("Ошибка расширения файла")
AttributeError: module 'flask.logging' has no attribute 'error'
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:31:05] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:32:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:32:55] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняю поиск
ERROR:root:Ошибка БД
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:32:58] "GET /search?s=кот HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:37:20] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:37:20] "[36mGET /static/styles/style.css HTTP/1.1[0m" 304 -
ERROR:root:Ошибка расширения файла
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:37:23] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:37:33] "GET /post HTTP/1.1" 200 -
ERROR:root:Ошибка размера файла
INFO:werkzeug:127.0.0.1 - - [01/Aug/2022 01:37:39] "[31m[1mPOST /post HTTP/1.1[0m" 413 -
